In [54]:
from tensorflow.keras.preprocessing.text import one_hot

In [55]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [56]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [57]:
## Define the vocabulary size
vocab_size = 10000

In [58]:
## one hot representation for every word
oneHotRepresentation = [one_hot(words, vocab_size)for words in sent]

In [59]:
oneHotRepresentation

[[8520, 67, 9668, 4419],
 [8520, 67, 9668, 8068],
 [8520, 4382, 9668, 4312],
 [7308, 4282, 1036, 7225],
 [7308, 4282, 1036, 6475, 1021],
 [8415, 8520, 3099, 9668, 2655],
 [4383, 5114, 7491, 6475]]

In [60]:
## Word embedding representation
from tensorflow.keras.layers import Embedding, Input
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [61]:
import numpy as np 

In [62]:
sent_length = 8
embedded_docs = pad_sequences(oneHotRepresentation, padding='pre', maxlen=sent_length)

In [63]:
print(embedded_docs)

[[   0    0    0    0 8520   67 9668 4419]
 [   0    0    0    0 8520   67 9668 8068]
 [   0    0    0    0 8520 4382 9668 4312]
 [   0    0    0    0 7308 4282 1036 7225]
 [   0    0    0 7308 4282 1036 6475 1021]
 [   0    0    0 8415 8520 3099 9668 2655]
 [   0    0    0    0 4383 5114 7491 6475]]


In [64]:
## Feature representation
dim = 10

In [ ]:
model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(
        input_dim=vocab_size,
        output_dim=dim
    )
])

model.compile(optimizer='adam', loss='mse')

In [66]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[[ 1.92880370e-02, -1.57204643e-02,  2.88784504e-04,
         -4.93188947e-03, -3.70940939e-02,  2.56335773e-02,
         -3.73761766e-02, -2.39935275e-02,  4.86187227e-02,
         -1.39117613e-02],
        [ 1.92880370e-02, -1.57204643e-02,  2.88784504e-04,
         -4.93188947e-03, -3.70940939e-02,  2.56335773e-02,
         -3.73761766e-02, -2.39935275e-02,  4.86187227e-02,
         -1.39117613e-02],
        [ 1.92880370e-02, -1.57204643e-02,  2.88784504e-04,
         -4.93188947e-03, -3.70940939e-02,  2.56335773e-02,
         -3.73761766e-02, -2.39935275e-02,  4.86187227e-02,
         -1.39117613e-02],
        [ 1.92880370e-02, -1.57204643e-02,  2.88784504e-04,
         -4.93188947e-03, -3.70940939e-02,  2.56335773e-02,
         -3.73761766e-02, -2.39935275e-02,  4.86187227e-02,
         -1.39117613e-02],
        [ 2.23103911e-03, -8.19237158e-03,  2.63536237e-02,
          2.54939906e-02, -3.74755487e-02, -3.67033258e-02,
          6.77537173e-04,  3.63466889e-03,  8.635744